### ISSUE TITLE
backdoors-and-breaches.pcio - Visual Issue - Blank

### ISSUE THREAD

**Issue by PAC256-coder** [FirmGuardian/backdoors-and-breaches-pcio#1]
Once you loaded "backdoors-and-breaches.pcio" in https://playingcards.io/ the cards looks white. The cards folder are located in the same path.

**Comment by Ciznit** [comment]
Just downloaded the pcio file and created a new game, all the card images loaded. Sometimes the site is slow to import. Try importing the game file again and letting it sit there for awhile if the cards are blank.

**Comment by PAC256-coder** [comment]
@Ciznit I waited more than a day and the images never loaded. I tried more than 20 times.

**Comment by Ciznit** [comment]
Try a different browser, also make sure you don't have any plugins like an ad blocker that may be interfering with the deck loading. I've got the cards to load fine with just downloading the pcio file and uploading it, so that's not the issue. The issue is either with your browser setup or with the playingcards.io site.

**Comment by Ciznit** [comment]
Here is the room I was able to create this morning: https://playingcards.io/gf833y

**Comment by PAC256-coder** [comment]
@Ciznit thank you very much. The issue was ZSCALER ;)
